# src/codegraphcontext/tools/indexing/constants.py
"""Shared constants for the indexing pipeline."""

# Maximum AST traversal depth before skipping a branch.
# Prevents RecursionError on deeply nested or autogenerated source files.
MAX_AST_DEPTH = 200

DEFAULT_IGNORE_PATTERNS = [
    "node_modules/",
    "venv/",
    ".venv/",
    "env/",
    ".env/",
    "dist/",
    "build/",
    "target/",
    "out/",
    ".git/",
    "__pycache__/",
    "*.png",
    "*.jpg",
    "*.jpeg",
    "*.gif",
    "*.svg",
    "*.mp4",
    "*.mp3",
    "*.zip",
    "*.tar",
    "*.gz",
]
