use crate::bespoke_event_handling::apply_bespoke_event_handling;
use crate::bespoke_event_handling::maybe_emit_hook_prompt_item_completed;
use crate::command_exec::CommandExecManager;
use crate::command_exec::StartCommandExecParams;
use crate::config_manager::ConfigManager;
use crate::error_code::INPUT_TOO_LARGE_ERROR_CODE;
use crate::error_code::invalid_params;
use crate::models::supported_models;
use crate::outgoing_message::ConnectionId;
use crate::outgoing_message::ConnectionRequestId;
use crate::outgoing_message::OutgoingMessageSender;
use crate::outgoing_message::RequestContext;
use crate::outgoing_message::ThreadScopedOutgoingMessageSender;
use crate::skills_watcher::SkillsWatcher;
use crate::thread_status::ThreadWatchManager;
use crate::thread_status::resolve_thread_status;
use chrono::Duration as ChronoDuration;
use chrono::SecondsFormat;
use ontocode_analytics::AnalyticsEventsClient;
use ontocode_analytics::AnalyticsJsonRpcError;
use ontocode_analytics::InputError;
use ontocode_analytics::TurnSteerRequestError;
use ontocode_app_server_protocol::Account;
use ontocode_app_server_protocol::AccountLoginCompletedNotification;
use ontocode_app_server_protocol::AccountUpdatedNotification;
use ontocode_app_server_protocol::AddCreditsNudgeCreditType;
use ontocode_app_server_protocol::AddCreditsNudgeEmailStatus;
use ontocode_app_server_protocol::AdditionalContextEntry;
use ontocode_app_server_protocol::AdditionalContextKind;
use ontocode_app_server_protocol::AppInfo;
use ontocode_app_server_protocol::AppListUpdatedNotification;
use ontocode_app_server_protocol::AppSummary;
use ontocode_app_server_protocol::AppsListParams;
use ontocode_app_server_protocol::AppsListResponse;
use ontocode_app_server_protocol::AskForApproval;
use ontocode_app_server_protocol::AuthMode;
use ontocode_app_server_protocol::CancelLoginAccountParams;
use ontocode_app_server_protocol::CancelLoginAccountResponse;
use ontocode_app_server_protocol::CancelLoginAccountStatus;
use ontocode_app_server_protocol::ClientInfo;
use ontocode_app_server_protocol::ClientRequest;
use ontocode_app_server_protocol::ClientResponsePayload;
use ontocode_app_server_protocol::CodexErrorInfo;
use ontocode_app_server_protocol::CollaborationModeListParams;
use ontocode_app_server_protocol::CollaborationModeListResponse;
use ontocode_app_server_protocol::CommandExecParams;
use ontocode_app_server_protocol::CommandExecResizeParams;
use ontocode_app_server_protocol::CommandExecTerminateParams;
use ontocode_app_server_protocol::CommandExecWriteParams;
use ontocode_app_server_protocol::ConfigWarningNotification;
use ontocode_app_server_protocol::ConversationGitInfo;
use ontocode_app_server_protocol::ConversationSummary;
use ontocode_app_server_protocol::DynamicToolSpec as ApiDynamicToolSpec;
use ontocode_app_server_protocol::EnvironmentAddParams;
use ontocode_app_server_protocol::EnvironmentAddResponse;
use ontocode_app_server_protocol::ExperimentalFeature as ApiExperimentalFeature;
use ontocode_app_server_protocol::ExperimentalFeatureListParams;
use ontocode_app_server_protocol::ExperimentalFeatureListResponse;
use ontocode_app_server_protocol::ExperimentalFeatureStage as ApiExperimentalFeatureStage;
use ontocode_app_server_protocol::FeedbackUploadParams;
use ontocode_app_server_protocol::FeedbackUploadResponse;
use ontocode_app_server_protocol::GetAccountParams;
use ontocode_app_server_protocol::GetAccountRateLimitsResponse;
use ontocode_app_server_protocol::GetAccountResponse;
use ontocode_app_server_protocol::GetAuthStatusParams;
use ontocode_app_server_protocol::GetAuthStatusResponse;
use ontocode_app_server_protocol::GetConversationSummaryParams;
use ontocode_app_server_protocol::GetConversationSummaryResponse;
use ontocode_app_server_protocol::GitDiffToRemoteParams;
use ontocode_app_server_protocol::GitDiffToRemoteResponse;
use ontocode_app_server_protocol::GitInfo as ApiGitInfo;
use ontocode_app_server_protocol::HookMetadata;
use ontocode_app_server_protocol::HooksListParams;
use ontocode_app_server_protocol::HooksListResponse;
use ontocode_app_server_protocol::InitializeParams;
use ontocode_app_server_protocol::InitializeResponse;
use ontocode_app_server_protocol::JSONRPCErrorError;
use ontocode_app_server_protocol::ListMcpServerStatusParams;
use ontocode_app_server_protocol::ListMcpServerStatusResponse;
use ontocode_app_server_protocol::LoginAccountParams;
use ontocode_app_server_protocol::LoginAccountResponse;
use ontocode_app_server_protocol::LoginApiKeyParams;
use ontocode_app_server_protocol::LogoutAccountResponse;
use ontocode_app_server_protocol::MarketplaceAddParams;
use ontocode_app_server_protocol::MarketplaceAddResponse;
use ontocode_app_server_protocol::MarketplaceInterface;
use ontocode_app_server_protocol::MarketplaceRemoveParams;
use ontocode_app_server_protocol::MarketplaceRemoveResponse;
use ontocode_app_server_protocol::MarketplaceUpgradeErrorInfo;
use ontocode_app_server_protocol::MarketplaceUpgradeParams;
use ontocode_app_server_protocol::MarketplaceUpgradeResponse;
use ontocode_app_server_protocol::McpResourceReadParams;
use ontocode_app_server_protocol::McpResourceReadResponse;
use ontocode_app_server_protocol::McpServerOauthLoginCompletedNotification;
use ontocode_app_server_protocol::McpServerOauthLoginParams;
use ontocode_app_server_protocol::McpServerOauthLoginResponse;
use ontocode_app_server_protocol::McpServerRefreshResponse;
use ontocode_app_server_protocol::McpServerStatus;
use ontocode_app_server_protocol::McpServerStatusDetail;
use ontocode_app_server_protocol::McpServerToolCallParams;
use ontocode_app_server_protocol::McpServerToolCallResponse;
use ontocode_app_server_protocol::MemoryResetResponse;
use ontocode_app_server_protocol::MockExperimentalMethodParams;
use ontocode_app_server_protocol::MockExperimentalMethodResponse;
use ontocode_app_server_protocol::ModelListParams;
use ontocode_app_server_protocol::ModelListResponse;
use ontocode_app_server_protocol::PermissionProfileListParams;
use ontocode_app_server_protocol::PermissionProfileListResponse;
use ontocode_app_server_protocol::PermissionProfileSummary;
use ontocode_app_server_protocol::PluginDetail;
use ontocode_app_server_protocol::PluginInstallParams;
use ontocode_app_server_protocol::PluginInstallResponse;
use ontocode_app_server_protocol::PluginInstalledParams;
use ontocode_app_server_protocol::PluginInstalledResponse;
use ontocode_app_server_protocol::PluginInterface;
use ontocode_app_server_protocol::PluginListMarketplaceKind;
use ontocode_app_server_protocol::PluginListParams;
use ontocode_app_server_protocol::PluginListResponse;
use ontocode_app_server_protocol::PluginMarketplaceEntry;
use ontocode_app_server_protocol::PluginReadParams;
use ontocode_app_server_protocol::PluginReadResponse;
use ontocode_app_server_protocol::PluginShareCheckoutParams;
use ontocode_app_server_protocol::PluginShareCheckoutResponse;
use ontocode_app_server_protocol::PluginShareContext;
use ontocode_app_server_protocol::PluginShareDeleteParams;
use ontocode_app_server_protocol::PluginShareDeleteResponse;
use ontocode_app_server_protocol::PluginShareDiscoverability;
use ontocode_app_server_protocol::PluginShareListItem;
use ontocode_app_server_protocol::PluginShareListParams;
use ontocode_app_server_protocol::PluginShareListResponse;
use ontocode_app_server_protocol::PluginSharePrincipal;
use ontocode_app_server_protocol::PluginSharePrincipalType;
use ontocode_app_server_protocol::PluginShareSaveParams;
use ontocode_app_server_protocol::PluginShareSaveResponse;
use ontocode_app_server_protocol::PluginShareTarget;
use ontocode_app_server_protocol::PluginShareUpdateDiscoverability;
use ontocode_app_server_protocol::PluginShareUpdateTargetsParams;
use ontocode_app_server_protocol::PluginShareUpdateTargetsResponse;
use ontocode_app_server_protocol::PluginSkillReadParams;
use ontocode_app_server_protocol::PluginSkillReadResponse;
use ontocode_app_server_protocol::PluginSource;
use ontocode_app_server_protocol::PluginSummary;
use ontocode_app_server_protocol::PluginUninstallParams;
use ontocode_app_server_protocol::PluginUninstallResponse;
use ontocode_app_server_protocol::RequestId;
use ontocode_app_server_protocol::ReviewDelivery as ApiReviewDelivery;
use ontocode_app_server_protocol::ReviewStartParams;
use ontocode_app_server_protocol::ReviewStartResponse;
use ontocode_app_server_protocol::ReviewTarget as ApiReviewTarget;
use ontocode_app_server_protocol::SandboxMode;
use ontocode_app_server_protocol::SendAddCreditsNudgeEmailParams;
use ontocode_app_server_protocol::SendAddCreditsNudgeEmailResponse;
use ontocode_app_server_protocol::ServerNotification;
use ontocode_app_server_protocol::ServerRequestResolvedNotification;
use ontocode_app_server_protocol::SkillSummary;
use ontocode_app_server_protocol::SkillsConfigWriteParams;
use ontocode_app_server_protocol::SkillsConfigWriteResponse;
use ontocode_app_server_protocol::SkillsExtraRootsSetParams;
use ontocode_app_server_protocol::SkillsExtraRootsSetResponse;
use ontocode_app_server_protocol::SkillsListParams;
use ontocode_app_server_protocol::SkillsListResponse;
use ontocode_app_server_protocol::SortDirection;
use ontocode_app_server_protocol::Thread;
use ontocode_app_server_protocol::ThreadApproveGuardianDeniedActionParams;
use ontocode_app_server_protocol::ThreadApproveGuardianDeniedActionResponse;
use ontocode_app_server_protocol::ThreadArchiveParams;
use ontocode_app_server_protocol::ThreadArchiveResponse;
use ontocode_app_server_protocol::ThreadArchivedNotification;
use ontocode_app_server_protocol::ThreadBackgroundTerminalsCleanParams;
use ontocode_app_server_protocol::ThreadBackgroundTerminalsCleanResponse;
use ontocode_app_server_protocol::ThreadClosedNotification;
use ontocode_app_server_protocol::ThreadCompactStartParams;
use ontocode_app_server_protocol::ThreadCompactStartResponse;
use ontocode_app_server_protocol::ThreadDecrementElicitationParams;
use ontocode_app_server_protocol::ThreadDecrementElicitationResponse;
use ontocode_app_server_protocol::ThreadForkParams;
use ontocode_app_server_protocol::ThreadForkResponse;
use ontocode_app_server_protocol::ThreadGoal;
use ontocode_app_server_protocol::ThreadGoalClearParams;
use ontocode_app_server_protocol::ThreadGoalClearResponse;
use ontocode_app_server_protocol::ThreadGoalClearedNotification;
use ontocode_app_server_protocol::ThreadGoalGetParams;
use ontocode_app_server_protocol::ThreadGoalGetResponse;
use ontocode_app_server_protocol::ThreadGoalSetParams;
use ontocode_app_server_protocol::ThreadGoalSetResponse;
use ontocode_app_server_protocol::ThreadGoalStatus;
use ontocode_app_server_protocol::ThreadGoalUpdatedNotification;
use ontocode_app_server_protocol::ThreadHistoryBuilder;
use ontocode_app_server_protocol::ThreadIncrementElicitationParams;
use ontocode_app_server_protocol::ThreadIncrementElicitationResponse;
use ontocode_app_server_protocol::ThreadInjectItemsParams;
use ontocode_app_server_protocol::ThreadInjectItemsResponse;
use ontocode_app_server_protocol::ThreadItem;
use ontocode_app_server_protocol::ThreadListCwdFilter;
use ontocode_app_server_protocol::ThreadListParams;
use ontocode_app_server_protocol::ThreadListResponse;
use ontocode_app_server_protocol::ThreadLoadedListParams;
use ontocode_app_server_protocol::ThreadLoadedListResponse;
use ontocode_app_server_protocol::ThreadMemoryModeSetParams;
use ontocode_app_server_protocol::ThreadMemoryModeSetResponse;
use ontocode_app_server_protocol::ThreadMetadataGitInfoUpdateParams;
use ontocode_app_server_protocol::ThreadMetadataUpdateParams;
use ontocode_app_server_protocol::ThreadMetadataUpdateResponse;
use ontocode_app_server_protocol::ThreadNameUpdatedNotification;
use ontocode_app_server_protocol::ThreadReadParams;
use ontocode_app_server_protocol::ThreadReadResponse;
use ontocode_app_server_protocol::ThreadRealtimeAppendAudioParams;
use ontocode_app_server_protocol::ThreadRealtimeAppendAudioResponse;
use ontocode_app_server_protocol::ThreadRealtimeAppendTextParams;
use ontocode_app_server_protocol::ThreadRealtimeAppendTextResponse;
use ontocode_app_server_protocol::ThreadRealtimeListVoicesResponse;
use ontocode_app_server_protocol::ThreadRealtimeStartParams;
use ontocode_app_server_protocol::ThreadRealtimeStartResponse;
use ontocode_app_server_protocol::ThreadRealtimeStartTransport;
use ontocode_app_server_protocol::ThreadRealtimeStopParams;
use ontocode_app_server_protocol::ThreadRealtimeStopResponse;
use ontocode_app_server_protocol::ThreadResumeInitialTurnsPageParams;
use ontocode_app_server_protocol::ThreadResumeParams;
use ontocode_app_server_protocol::ThreadResumeResponse;
use ontocode_app_server_protocol::ThreadRollbackParams;
use ontocode_app_server_protocol::ThreadSearchParams;
use ontocode_app_server_protocol::ThreadSearchResponse;
use ontocode_app_server_protocol::ThreadSearchResult;
use ontocode_app_server_protocol::ThreadSetNameParams;
use ontocode_app_server_protocol::ThreadSetNameResponse;
use ontocode_app_server_protocol::ThreadSettings;
use ontocode_app_server_protocol::ThreadSettingsUpdateParams;
use ontocode_app_server_protocol::ThreadSettingsUpdateResponse;
use ontocode_app_server_protocol::ThreadShellCommandParams;
use ontocode_app_server_protocol::ThreadShellCommandResponse;
use ontocode_app_server_protocol::ThreadSortKey;
use ontocode_app_server_protocol::ThreadSourceKind;
use ontocode_app_server_protocol::ThreadStartParams;
use ontocode_app_server_protocol::ThreadStartResponse;
use ontocode_app_server_protocol::ThreadStartedNotification;
use ontocode_app_server_protocol::ThreadStatus;
use ontocode_app_server_protocol::ThreadTurnsItemsListParams;
use ontocode_app_server_protocol::ThreadTurnsItemsListResponse;
use ontocode_app_server_protocol::ThreadTurnsListParams;
use ontocode_app_server_protocol::ThreadTurnsListResponse;
use ontocode_app_server_protocol::ThreadUnarchiveParams;
use ontocode_app_server_protocol::ThreadUnarchiveResponse;
use ontocode_app_server_protocol::ThreadUnarchivedNotification;
use ontocode_app_server_protocol::ThreadUnsubscribeParams;
use ontocode_app_server_protocol::ThreadUnsubscribeResponse;
use ontocode_app_server_protocol::ThreadUnsubscribeStatus;
use ontocode_app_server_protocol::Turn;
use ontocode_app_server_protocol::TurnEnvironmentParams;
use ontocode_app_server_protocol::TurnError;
use ontocode_app_server_protocol::TurnInterruptParams;
use ontocode_app_server_protocol::TurnInterruptResponse;
use ontocode_app_server_protocol::TurnItemsView;
use ontocode_app_server_protocol::TurnStartParams;
use ontocode_app_server_protocol::TurnStartResponse;
use ontocode_app_server_protocol::TurnStatus;
use ontocode_app_server_protocol::TurnSteerParams;
use ontocode_app_server_protocol::TurnSteerResponse;
use ontocode_app_server_protocol::UserInput as V2UserInput;
use ontocode_app_server_protocol::WindowsSandboxReadiness;
use ontocode_app_server_protocol::WindowsSandboxReadinessResponse;
use ontocode_app_server_protocol::WindowsSandboxSetupCompletedNotification;
use ontocode_app_server_protocol::WindowsSandboxSetupMode;
use ontocode_app_server_protocol::WindowsSandboxSetupStartParams;
use ontocode_app_server_protocol::WindowsSandboxSetupStartResponse;
use ontocode_arg0::Arg0DispatchPaths;
use ontocode_backend_client::AddCreditsNudgeCreditType as BackendAddCreditsNudgeCreditType;
use ontocode_backend_client::Client as BackendClient;
use ontocode_chatgpt::connectors;
use ontocode_chatgpt::workspace_settings;
use ontocode_config::CloudConfigBundleLoadError;
use ontocode_config::CloudConfigBundleLoadErrorCode;
use ontocode_config::ConfigLayerStack;
use ontocode_config::loader::project_trust_key;
use ontocode_config::types::McpServerTransportConfig;
use ontocode_core::CodexThread;
use ontocode_core::CodexThreadSettingsOverrides;
use ontocode_core::ExternalGoalPreviousStatus;
use ontocode_core::ExternalGoalSet;
use ontocode_core::ForkSnapshot;
use ontocode_core::NewThread;
#[cfg(test)]
use ontocode_core::SessionMeta;
use ontocode_core::StartThreadOptions;
use ontocode_core::SteerInputError;
use ontocode_core::ThreadConfigSnapshot;
use ontocode_core::ThreadManager;
use ontocode_core::config::Config;
use ontocode_core::config::ConfigOverrides;
use ontocode_core::config::NetworkProxyAuditMetadata;
use ontocode_core::config::edit::ConfigEdit;
use ontocode_core::config::edit::ConfigEditsBuilder;
use ontocode_core::connectors::AccessibleConnectorsStatus;
use ontocode_core::exec::ExecCapturePolicy;
use ontocode_core::exec::ExecExpiration;
use ontocode_core::exec::ExecParams;
use ontocode_core::exec_env::create_env;
use ontocode_core::path_utils;
#[cfg(test)]
use ontocode_core::read_head_for_summary;
use ontocode_core::sandboxing::SandboxPermissions;
use ontocode_core::windows_sandbox::WindowsSandboxLevelExt;
use ontocode_core::windows_sandbox::WindowsSandboxSetupMode as CoreWindowsSandboxSetupMode;
use ontocode_core::windows_sandbox::WindowsSandboxSetupRequest;
use ontocode_core::windows_sandbox::sandbox_setup_is_complete;
use ontocode_core_plugins::PluginInstallError as CorePluginInstallError;
use ontocode_core_plugins::PluginInstallRequest;
use ontocode_core_plugins::PluginLoadOutcome;
use ontocode_core_plugins::PluginReadRequest;
use ontocode_core_plugins::PluginUninstallError as CorePluginUninstallError;
use ontocode_core_plugins::loader::load_plugin_apps;
use ontocode_core_plugins::loader::load_plugin_mcp_servers;
use ontocode_core_plugins::loader::plugin_telemetry_metadata_from_root;
use ontocode_core_plugins::manifest::PluginManifestInterface;
use ontocode_core_plugins::marketplace::MarketplaceError;
use ontocode_core_plugins::marketplace::MarketplacePluginSource;
use ontocode_core_plugins::marketplace_add::MarketplaceAddError;
use ontocode_core_plugins::marketplace_add::MarketplaceAddRequest;
use ontocode_core_plugins::marketplace_add::add_marketplace as add_marketplace_to_codex_home;
use ontocode_core_plugins::marketplace_remove::MarketplaceRemoveError;
use ontocode_core_plugins::marketplace_remove::MarketplaceRemoveRequest as CoreMarketplaceRemoveRequest;
use ontocode_core_plugins::marketplace_remove::remove_marketplace;
use ontocode_core_plugins::remote::RemoteMarketplace;
use ontocode_core_plugins::remote::RemoteMarketplaceSource;
use ontocode_core_plugins::remote::RemotePluginCatalogError;
use ontocode_core_plugins::remote::RemotePluginDetail as RemoteCatalogPluginDetail;
use ontocode_core_plugins::remote::RemotePluginServiceConfig;
use ontocode_core_plugins::remote::RemotePluginShareContext as RemoteCatalogPluginShareContext;
use ontocode_core_plugins::remote::RemotePluginShareSummary as RemoteCatalogPluginShareSummary;
use ontocode_core_plugins::remote::RemotePluginSummary as RemoteCatalogPluginSummary;
use ontocode_exec_server::EnvironmentManager;
use ontocode_exec_server::LOCAL_FS;
use ontocode_features::FEATURES;
use ontocode_features::Feature;
use ontocode_features::Stage;
use ontocode_feedback::CodexFeedback;
use ontocode_feedback::FeedbackAttachmentPath;
use ontocode_feedback::FeedbackUploadOptions;
use ontocode_git_utils::git_diff_to_remote;
use ontocode_git_utils::resolve_root_git_project_for_trust;
use ontocode_login::AuthManager;
use ontocode_login::CLIENT_ID;
use ontocode_login::CodexAuth;
use ontocode_login::GEMINI_OAUTH_CLIENT_ID;
use ontocode_login::GeminiLoginServerOptions;
use ontocode_login::ServerOptions as LoginServerOptions;
use ontocode_login::ShutdownHandle;
use ontocode_login::auth::login_with_chatgpt_auth_tokens;
use ontocode_login::complete_device_code_login;
use ontocode_login::login_with_api_key;
use ontocode_login::request_device_code;
use ontocode_login::run_gemini_login_server;
use ontocode_login::run_login_server;
use ontocode_mcp::McpRuntimeContext;
use ontocode_mcp::McpServerStatusSnapshot;
use ontocode_mcp::McpSnapshotDetail;
use ontocode_mcp::collect_mcp_server_status_snapshot_with_detail;
use ontocode_mcp::discover_supported_scopes;
use ontocode_mcp::read_mcp_resource as read_mcp_resource_without_thread;
use ontocode_mcp::resolve_oauth_scopes;
use ontocode_memories_write::clear_memory_roots_contents;
use ontocode_model_provider::ProviderAccountError;
use ontocode_model_provider::create_model_provider;
use ontocode_models_manager::collaboration_mode_presets::builtin_collaboration_mode_presets;
use ontocode_protocol::ThreadId;
use ontocode_protocol::config_types::CollaborationMode;
use ontocode_protocol::config_types::ForcedLoginMethod;
use ontocode_protocol::config_types::Personality;
use ontocode_protocol::config_types::ReasoningSummary;
use ontocode_protocol::config_types::TrustLevel;
use ontocode_protocol::config_types::WindowsSandboxLevel;
use ontocode_protocol::dynamic_tools::DynamicToolSpec as CoreDynamicToolSpec;
use ontocode_protocol::error::CodexErr;
use ontocode_protocol::error::Result as CodexResult;
#[cfg(test)]
use ontocode_protocol::items::TurnItem;
use ontocode_protocol::models::BUILT_IN_PERMISSION_PROFILE_DANGER_FULL_ACCESS;
use ontocode_protocol::models::BUILT_IN_PERMISSION_PROFILE_READ_ONLY;
use ontocode_protocol::models::BUILT_IN_PERMISSION_PROFILE_WORKSPACE;
use ontocode_protocol::models::ResponseItem;
use ontocode_protocol::openai_models::ReasoningEffort;
#[cfg(test)]
use ontocode_protocol::permissions::FileSystemSandboxPolicy;
use ontocode_protocol::protocol::AgentStatus;
use ontocode_protocol::protocol::ConversationAudioParams;
use ontocode_protocol::protocol::ConversationStartParams;
use ontocode_protocol::protocol::ConversationStartTransport;
use ontocode_protocol::protocol::ConversationTextParams;
use ontocode_protocol::protocol::EventMsg;
#[cfg(test)]
use ontocode_protocol::protocol::GitInfo as CoreGitInfo;
use ontocode_protocol::protocol::InitialHistory;
use ontocode_protocol::protocol::McpAuthStatus as CoreMcpAuthStatus;
use ontocode_protocol::protocol::Op;
use ontocode_protocol::protocol::RateLimitSnapshot as CoreRateLimitSnapshot;
use ontocode_protocol::protocol::RealtimeVoicesList;
use ontocode_protocol::protocol::ResumedHistory;
use ontocode_protocol::protocol::ReviewDelivery as CoreReviewDelivery;
use ontocode_protocol::protocol::ReviewRequest;
use ontocode_protocol::protocol::ReviewTarget as CoreReviewTarget;
use ontocode_protocol::protocol::RolloutItem;
use ontocode_protocol::protocol::SessionConfiguredEvent;
#[cfg(test)]
use ontocode_protocol::protocol::SessionMetaLine;
use ontocode_protocol::protocol::TurnEnvironmentSelection;
use ontocode_protocol::protocol::USER_MESSAGE_BEGIN;
use ontocode_protocol::protocol::W3cTraceContext;
use ontocode_protocol::user_input::MAX_USER_INPUT_TEXT_CHARS;
use ontocode_protocol::user_input::UserInput as CoreInputItem;
use ontocode_rmcp_client::perform_oauth_login_return_url;
use ontocode_rollout::is_persisted_rollout_item;
use ontocode_rollout::state_db::StateDbHandle;
use ontocode_rollout::state_db::reconcile_rollout;
use ontocode_state::ThreadMetadata;
use ontocode_state::log_db::LogDbLayer;
use ontocode_thread_store::ArchiveThreadParams as StoreArchiveThreadParams;
use ontocode_thread_store::GitInfoPatch as StoreGitInfoPatch;
use ontocode_thread_store::ListThreadsParams as StoreListThreadsParams;
use ontocode_thread_store::LocalThreadStore;
use ontocode_thread_store::ReadThreadByRolloutPathParams as StoreReadThreadByRolloutPathParams;
use ontocode_thread_store::ReadThreadParams as StoreReadThreadParams;
use ontocode_thread_store::SearchThreadsParams as StoreSearchThreadsParams;
use ontocode_thread_store::SortDirection as StoreSortDirection;
use ontocode_thread_store::StoredThread;
use ontocode_thread_store::ThreadMetadataPatch as StoreThreadMetadataPatch;
use ontocode_thread_store::ThreadSortKey as StoreThreadSortKey;
use ontocode_thread_store::ThreadStore;
use ontocode_thread_store::ThreadStoreError;
use ontocode_utils_absolute_path::AbsolutePathBuf;
use ontocode_utils_pty::DEFAULT_OUTPUT_BYTES_CAP;
use std::collections::BTreeMap;
use std::collections::HashMap;
use std::collections::HashSet;
use std::io::Error as IoError;
use std::path::Path;
use std::path::PathBuf;
use std::result::Result;
use std::sync::Arc;
use std::time::Duration;
use std::time::Instant;
use tokio::sync::Mutex;
use tokio::sync::Semaphore;
use tokio::sync::SemaphorePermit;
use tokio::sync::broadcast;
use tokio::sync::oneshot;
use tokio::sync::watch;
use tokio_util::sync::CancellationToken;
use tokio_util::sync::DropGuard;
use tokio_util::task::TaskTracker;
use toml::Value as TomlValue;
use tracing::Instrument;
use tracing::error;
use tracing::info;
use tracing::warn;
use uuid::Uuid;

#[cfg(test)]
use ontocode_app_server_protocol::ServerRequest;

mod account_processor;
mod apps_processor;
mod catalog_processor;
mod command_exec_processor;
mod config_processor;
mod environment_processor;
mod external_agent_config_processor;
mod feedback_doctor_report;
mod feedback_processor;
mod fs_processor;
mod git_processor;
mod initialize_processor;
mod marketplace_processor;
mod mcp_processor;
mod plugins;
mod process_exec_processor;
mod remote_control_processor;
mod search;
mod thread_processor;
mod token_usage_replay;
mod turn_processor;
mod windows_sandbox_processor;

pub(crate) use account_processor::AccountRequestProcessor;
pub(crate) use apps_processor::AppsRequestProcessor;
pub(crate) use catalog_processor::CatalogRequestProcessor;
pub(crate) use command_exec_processor::CommandExecRequestProcessor;
pub(crate) use config_processor::ConfigRequestProcessor;
pub(crate) use environment_processor::EnvironmentRequestProcessor;
pub(crate) use external_agent_config_processor::ExternalAgentConfigRequestProcessor;
pub(crate) use feedback_processor::FeedbackRequestProcessor;
pub(crate) use fs_processor::FsRequestProcessor;
pub(crate) use git_processor::GitRequestProcessor;
pub(crate) use initialize_processor::InitializeRequestProcessor;
pub(crate) use marketplace_processor::MarketplaceRequestProcessor;
pub(crate) use mcp_processor::McpRequestProcessor;
pub(crate) use plugins::PluginRequestProcessor;
pub(crate) use process_exec_processor::ProcessExecRequestProcessor;
pub(crate) use remote_control_processor::RemoteControlRequestProcessor;
pub(crate) use search::SearchRequestProcessor;
pub(crate) use thread_goal_processor::ThreadGoalRequestProcessor;
pub(crate) use thread_processor::ThreadRequestProcessor;
pub(crate) use turn_processor::TurnRequestProcessor;
pub(crate) use windows_sandbox_processor::WindowsSandboxRequestProcessor;

use crate::error_code::internal_error;
use crate::error_code::invalid_request;
use crate::filters::compute_source_filters;
use crate::filters::source_kind_matches;
use crate::thread_state::ConnectionCapabilities;
use crate::thread_state::ThreadListenerCommand;
use crate::thread_state::ThreadState;
use crate::thread_state::ThreadStateManager;
use token_usage_replay::latest_token_usage_turn_id_from_rollout_items;
use token_usage_replay::send_thread_token_usage_update_to_connection;

mod config_errors;
mod request_errors;
mod thread_goal_processor;
mod thread_lifecycle;
mod thread_resume_redaction;
mod thread_summary;

use self::config_errors::*;
use self::request_errors::*;
use self::thread_goal_processor::api_thread_goal_from_state;
use self::thread_lifecycle::*;
use self::thread_resume_redaction::*;
use self::thread_summary::*;

pub(crate) use self::thread_lifecycle::populate_thread_turns_from_history;
pub(crate) use self::thread_processor::thread_from_stored_thread;
#[cfg(test)]
pub(crate) use self::thread_summary::read_summary_from_rollout;
#[cfg(test)]
pub(crate) use self::thread_summary::summary_to_thread;
pub(crate) use self::thread_summary::thread_settings_from_config_snapshot;
pub(crate) use self::thread_summary::thread_settings_from_core_snapshot;

pub(crate) fn build_api_turns_from_rollout_items(items: &[RolloutItem]) -> Vec<Turn> {
    let mut builder = ThreadHistoryBuilder::new();
    for item in items {
        if is_persisted_rollout_item(item) {
            builder.handle_rollout_item(item);
        }
    }
    builder.finish()
}
